### ISSUE TITLE
Block fuel is always loading max 51280 (lb)

### ISSUE THREAD

**Issue by Simssmith** [hotbso/toliss_simbrief#2]
When I fetch OFP fuel load is displayed correctly in the widget (28122 lb). However when I click Xfer Load data to ISCS it always shows 51280 in Toliss ISCS .

![image](https://user-images.githubusercontent.com/26805400/121812530-ca074200-cc2d-11eb-8a18-1f5f45cd0179.png)

**Comment by hotbso** [comment]
I think that was fixed meanwhile.
